baseURL               = "https://www.longyu.cool"
languageCode          = "zh-CN"
title                 = "提瓦特爱好家协会"
theme                 = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "docs"


[params]
    author        = "longyu"
    description   = "提瓦特爱好家协会 | longyu的导航站 | 提瓦特导航表 | Hugo 主题 BY Bio IT 爱好者"
    siteurl       = "./"
    upload        = "https://space.bilibili.com/90158726"  # 左侧导航栏的"网站提交"
    about         = "https://shumlab.com/cookbook/webstack-hugo"   # 左侧导航栏的"关于导航"页面(./about)
    repository    = "https://github.com/shenweiyan/WebStack-Hugo"  
    enablePreLoad = true		    		           # 网站完全打开前预加载动画
    textPreLoad   = "提瓦特爱好家协会导航站" 		           # 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = true                                          # 默认展开左侧边导航栏
    logosPath     = "assets/images/logos"			   # 网站每个导航地址logo存放地址
    defaultLogo   = "assets/images/logos/default.webp"             # logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功

[params.seo]    
    baiduhmid     = 'c9cc0e72b76147d36763e6c5c046cbde'             # 百度统计 hm.src 的 ID
    baiduSiteVer  = 'codeva-cCAOSG8MBO'                            # 百度HTML标签验证(baidu-site-verification)

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "assets/images/favicon.png"
    searchImageL      = "assets/images/bg-dna.jpg"		#搜索部分浅色背景图
    searchImageD      = "assets/images/bg-dna.jpg"		#搜索部分深色背景图
    logoExpandLight   = "assets/images/bt8-expand-light.png"
    logoExpandDark    = "assets/images/bt8-expand-dark.png"
    logoCollapseLight = "assets/images/bt.png"
    logoCollapseDark  = "assets/images/bt.png"
    
[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '本站内容源自互联网，如有内容侵犯了你的权益，请联系删除相关内容，联系邮箱：longyu_w@foxmail.com <br/>&copy; 2021 - {year} By [WebStack-Hugo](https://github.com/shenweiyan/WebStack-Hugo) | [Bio IT 爱好者](https://www.bioitee.com/) | [冀ICP备2022000685号-1](https://beian.miit.gov.cn)<br/>'
