# Generated by Django 4.1.7 on 2023-05-23 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='类别名称')),
                ('icon', models.CharField(default='fa-star', max_length=20, verbose_name='图标')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='friendlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='网站名称')),
                ('url', models.CharField(default='#', max_length=256, verbose_name='网站链接')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='提瓦特爱好家协会', max_length=256, verbose_name='标题')),
                ('titleloader', models.CharField(default='提瓦特爱好家协会导航站加载中...', max_length=256, verbose_name='加载中')),
                ('uplloadpage', models.CharField(default='https://space.bilibili.com/90158726', max_length=256, verbose_name='网站提交')),
                ('about', models.CharField(default='https://space.bilibili.com/90158726', max_length=256, verbose_name='关于网站')),
                ('end', models.CharField(default='本站内容源自互联网，如有内容侵犯了你的权益，请联系删除相关内容，联系邮箱：longyu_w@foxmail.com <br/>&copy; 2021 - {year} By [WebStack-Hugo](https://github.com/shenweiyan/WebStack-Hugo) | [Bio IT 爱好者](https://www.bioitee.com/) | [冀ICP备2022000685号-1](https://beian.miit.gov.cn)', max_length=256, verbose_name='关于网站')),
            ],
            options={
                'verbose_name': '主页设置',
                'verbose_name_plural': '主页设置',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='子类别名称')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QWebStack2.category')),
            ],
            options={
                'verbose_name': '子分类',
                'verbose_name_plural': '子分类',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='#', max_length=256, verbose_name='网站链接')),
                ('logo_url', models.CharField(default='', max_length=256, verbose_name='logo链接')),
                ('name', models.CharField(max_length=20, verbose_name='网站名称')),
                ('describtion', models.TextField(blank=True, verbose_name='网站简介')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QWebStack2.subcategory')),
            ],
            options={
                'verbose_name': '站点',
                'verbose_name_plural': '站点',
                'ordering': ['id'],
            },
        ),
    ]
