# Generated by Django 4.1.7 on 2023-05-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QWebStack2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='提瓦特爱好家协会', max_length=256, verbose_name='标题')),
                ('titleloader', models.CharField(default='提瓦特爱好家协会导航站加载中...', max_length=256, verbose_name='加载中')),
                ('uplloadpage', models.CharField(default='https://space.bilibili.com/90158726', max_length=256, verbose_name='网站提交')),
                ('about', models.CharField(default='https://space.bilibili.com/90158726', max_length=256, verbose_name='关于网站')),
                ('end', models.CharField(default='本站内容源自互联网，如有内容侵犯了你的权益，请联系删除相关内容，联系邮箱：longyu_w@foxmail.com <br/>&copy; 2021 - {year} By [WebStack-Hugo](https://github.com/shenweiyan/WebStack-Hugo) | [Bio IT 爱好者](https://www.bioitee.com/) | [冀ICP备2022000685号-1](https://beian.miit.gov.cn)', max_length=256, verbose_name='关于网站')),
            ],
            options={
                'verbose_name': '主页设置',
                'verbose_name_plural': '主页设置',
                'ordering': ['id'],
            },
        ),
    ]
