# Generated by Django 4.1.7 on 2023-05-21 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QWebStack2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QWebStack2.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QWebStack2.category'),
        ),
    ]
