# Generated by Django 4.1.7 on 2023-04-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_category_rank_website_rank_alter_website_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='logo_url',
            field=models.CharField(default='', max_length=256, verbose_name='logo链接'),
        ),
    ]
